# Generated by Django 2.2.1 on 2019-05-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileowner',
            name='picture',
            field=models.URLField(default='https://www.tenforums.com/geek/gars/images/2/types/thumb__ser.png'),
        ),
    ]
