# Generated by Django 2.2.1 on 2019-05-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190523_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileowner',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileowner',
            name='description',
            field=models.TextField(default='No_description'),
        ),
        migrations.AddField(
            model_name='profileowner',
            name='name',
            field=models.CharField(default='No_name_added', max_length=200),
        ),
    ]
